# See full config at https://github.com/backup-manager/symfony
bm_backup_manager:
    database:
        development:
            dsn: '%env(resolve:DATABASE_URL)%'
        production:
            dsn: '%env(resolve:DATABASE_URL)%'
    storage:
        local:
            type: Local
            root: '%kernel.cache_dir%/db'
        ftp:
            type: Ftp
            host: '%env(resolve:FTP_HOST)%'
            username: '%env(resolve:FTP_USER)%'
            password: '%env(resolve:FTP_PASS)%'
            root: /LMS-SODEPAC/
            port: 21
            passive: true
            ssl: false
            timeout: 30

