version: '3'

services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '000:80'
    volumes:
      - .:/var/www:delegated
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    restart: unless-stopped
    build: ./docker/php
    volumes:
      - .:/var/www:delegated
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      MYSQL_ROOT_PASSWORD: lms-sodepac
      MYSQL_DATABASE: lms-sodepac
      MYSQL_USER: lms-sodepac
      MYSQL_PASSWORD: lms-sodepac
    volumes:
      - db-data:/var/lib/mysql
      - ./var:/var/www/var
  redis:
    restart: unless-stopped
    image: redis:6-alpine
  messenger:
    build: ./docker/php
    volumes:
        - .:/var/www:delegated
    depends_on:
        - db
    restart: unless-stopped
    command: [ 'php', 'bin/console', 'messenger:consume', 'async', '--limit=10', '-vvv' ]
    environment:
      MESSENGER_TRANSPORT_DSN: redis://redis:6379/messages
      MESSENGER_TRANSPORT_FAILED_DSN: redis://redis:6379/messages_failed

  #Dev Tools
  adminer:
    image: adminer
    environment:
      APP_ENV: dev
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
    ports:
      - '8888:8080'
  mail:
    image: mailhog/mailhog
    ports:
      - '1080:8025'
  redis-gui:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
volumes:
  db-data:
