version: '3'

services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - .:/var/www:delegated
      - ./site.prod.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    links:
      - php
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/etc/letsencrypt --email sys@skyreka.com --agree-tos -d lab-sodepac.skyreka.com -d www.lab-sodepac.skyreka.com
  php:
    restart: unless-stopped
    build: ./docker/php
    volumes:
      - .:/var/www:delegated
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./var:/var/www/var
  redis:
    restart: unless-stopped
    image: redis:6-alpine
  messenger:
    build: ./docker/php
    volumes:
      - .:/var/www:delegated
    depends_on:
      - db
    restart: unless-stopped
    command: [ 'php', 'bin/console', 'messenger:consume', 'async', '--limit=10', '-vvv' ]
    environment:
      MESSENGER_TRANSPORT_DSN: redis://redis:6379/messages
      MESSENGER_TRANSPORT_FAILED_DSN: redis://redis:6379/messages_failed
volumes:
  db-data:

