---
- name: Symfony | Clone
  become: no
  git:
    repo: 'https://github.com/Skyreka/LMS-Sodepac.git'
    dest: "{{ root_path }}"
    version: "{{ GIT_BRANCH }}"
- name: Symfony | .env.local"
  become: no
  template:
    src: .env.local.j2
    force: no
    dest: "{{ root_path }}/.env.local"
- include_tasks: messenger.yml
- name: Symfony | Create var directory
  ansible.builtin.file:
    path: "{{ root_path }}/var"
    state: directory
- name: Symfony | Create public/uploads directory
  ansible.builtin.file:
    path: "{{ root_path }}/public/uploads"
    state: directory
- name: Symfony | var permission
  ansible.posix.acl:
    path: "{{ root_path }}/var"
    entity: "{{ ansible_user }}"
    etype: user
    default: yes
    permissions: rwx
    state: present
    recursive: yes
- name: Symfony | var permission www-data
  ansible.posix.acl:
    path: "{{ root_path }}/var"
    entity: "www-data"
    etype: user
    default: yes
    permissions: rwx
    state: present
    recursive: yes
- name: Symfony | var permission www-data
  ansible.posix.acl:
    path: "{{ root_path }}/var"
    entity: "www-data"
    etype: user
    permissions: rwx
    state: present
    recursive: yes
- name: Symfony | dossier uploads
  become: no
  file: state=directory path="{{ root_path }}/public/uploads"
- name: Symfony | uploads permission
  ansible.posix.acl:
    path: "{{ root_path }}/public/uploads"
    entity: www-data
    etype: user
    default: yes
    permissions: rwx
    state: present
    recursive: yes
- name: Symfony | uploads permission
  ansible.posix.acl:
    path: "{{ root_path }}/public/uploads"
    entity: www-data
    etype: user
    permissions: rwx
    state: present
    recursive: yes
- name: Symfony | uploads permission
  ansible.posix.acl:
    path: "{{ root_path }}/public/uploads"
    entity: "{{ ansible_user }}"
    etype: user
    default: yes
    permissions: rwx
    state: present
    recursive: yes
