monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: critical
            handler: nduplicated
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        deduplicated:
            type: deduplication
            handler: symfony_mailer
        symfony_mailer:
            type: symfony_mailer
            from_email: 'no-reply@skyreka.com'
            to_email: 'theodore.turpin@skyreka.com'
            subject: 'LMS-SODEPAC - An error occurred! %%message%%'
            level: debug
            formatter: monolog.formatter.html
            content_type: text/html
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
